input {
	kb_model = pc104
	kb_layout = us
	kb_variant = intl
	kb_options = terminate:ctrl_alt_bksp,caps:escape_shifted_capslock
	kb_rules = 
	
	numlock_by_default = false
	resolve_binds_by_sym = false
	
	repeat_rate = 25
	repeat_delay = 600

	sensitivity = 0.2
	accel_profile = flat
	force_no_accel = false
	
	rotation = 0
	left_handed = false

	scroll_points = 
	scroll_method = 
	scroll_button = 274
	scroll_button_lock = false
	scroll_factor = 1.0
	natural_scroll = false

	follow_mouse = 2
	follow_mouse_threshold = 0.0
	focus_on_close = 0
	mouse_refocus = true
	float_switch_override_focus = 0
	special_fallthrough = false
	off_window_axis_events = 1
	emulate_discrete_scroll = 0

	touchpad {
		disable_while_typing = true
		natural_scroll = false
		scroll_factor = 1.0
	
		middle_button_emulation = false
		tap_button_map = lrm
		clickfinger_behavior = false
		tap-to-click = true
		drag_lock = 0
		tap-and-drag = true
		flip_x = false
		flip_y = false
		drag_3fg = 0
	}

	touch_device {
		#transform = -1
		#output = Auto
		#enabled = true
	}
	
	virtualkeyboard {
		share_states = 2
		release_pressed_on_close = false
	}

	tablet {
		transform = -1
		output = 
		region_position = 0, 0
		absolute_region_position = false
		region_size = 0, 0
		left_handed = false
		active_area_size = 0, 0
		active_area_position = 0, 0
	}
}
